spring:
  liquibase:
    enabled: true
    change-log: classpath:changelog/changelog.yml
  application:
    name: pivo
  datasource:
    url: jdbc:postgresql://localhost:5432/pivodb
    username: application
    password: password
  jpa:
    show-sql: true           # Печатает SQL
    properties:
      hibernate:
        format_sql: true     # Форматирует SQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
beer-application:
  nanoid:
    size: 25
    alphabet: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-"
  urls:
    employee: "http://localhost:8081"
springdoc:
  swagger-ui:
    path: "/swagger"
    url: "/v3/api-docs"
    configUrl: "/v3/api-docs/swagger-config"